import type { Metadata } from "next";
import { Literata, Public_Sans } from "next/font/google";
import "./globals.css";
import { Header } from "../components/header";
import { Footer } from "../components/footer";

// Import Literata for headlines and accents
const literata = Literata({
  subsets: ["latin"],
  variable: "--font-literata",
  display: "swap",
});
// Import Public Sans for body text
const publicSans = Public_Sans({
  subsets: ["latin"],
  variable: "--font-public-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${literata.variable} ${publicSans.variable} antialiased`}>
      {/*
        Apply Public Sans as the default font for body text,
        and Literata for headlines using Tailwind's font-sans and font-serif classes.
        You can further customize this in globals.css or Tailwind config if needed.
      */}
      <body className="font-sans">
        <Header />
        {children}
        {/* Brutalist, minimal footer at the bottom of every page */}
        <Footer />
      </body>
    </html>
  );
}
